### ISSUE TITLE
Start a new branch to run evaluation results fro V3-V5 ( will close this and open a new branch to continue, because the stash process give error for the rebasing) 

### ISSUE THREAD

**Issue by liniiiiii** [VUB-HYDR/Wikimpacts#116]
- [x] run the script and get the L1 results 
- [x] **- case1: dev set, run fixing_json_inconsistency, V3 prompts GPT4o, all categories, l2/3 matching using mean score algorithm** 
- [x]  case2, dev set, run fixing_json_inconsistency, V3 prompts GPT4o, all categories, l2/3 matching using weights for matcher.py as Joakim proposed 
- [x] change the Country_Norm in matcher.py to Administrative_Area_Norm

after the process above, several things need to be checked @i-be-snek , thanks for the support of the evaluation process, after I run the pipeline today, I think you are working on the issue I found today or before. If anything is missing pls correct me, and anything need to support with the code-review, feel free to tag me. I will work on the visualization, and data gap fixing https://github.com/VUB-HYDR/Wikimpacts/issues/101#issue-2507615593 step by step. 

- [ ] Error when evaluating monetary in L1/L2/L3, the issue linked to https://github.com/VUB-HYDR/Wikimpacts/issues/80#issue-2473367917, in processing (Shorouq) 
- [x] Check the Administrative_Areas_Norm in L1, the current normalization didn't covert non-country location to country, https://github.com/VUB-HYDR/Wikimpacts/issues/112#issuecomment-2353081548 in processing (Shorouq) 
- [x] deal with data type error https://github.com/VUB-HYDR/Wikimpacts/issues/117#issue-2536577467 in processing (Shorouq)
