### ISSUE TITLE
process full run database (to do branch) 

### ISSUE THREAD

**Issue by liniiiiii** [VUB-HYDR/Wikimpacts#173]
with the fullrun experiment finished, we have the raw parsed output. To make the database consistent, and provide a version that user can directly use, we will process the database with follows

- [x] some events have country1 or country2, they are not capturing real events (resolved in #184)
- [x] The GID column is sometimes None but it should be `[]` (resolved in #179)
- [x] Only allow specific values of event types, anything outside that list should be removed before being placed into the database (resolved in #181)
- [ ] currency conversion and inflation adjusted for L1-L3  (resolved in ~#180~ #191)
- [x] captured "null" location (edit: added 20/oct/2024) -- may be a systematic error. (resolved in #183)
- [x] the data gap, make sure all fields, L1>=L2>=L3 (resolved in #174)

- Time, the *_Year in L1 should cover L2 and L3, eg, *_Year in L1 are 2020,2021, L2 and L3 could not have *_Year 2019,2023
- Location, the Admin_Areas in L1, should cover all Admin_Areas in L2, and Admin_Areas in L2 should cover all Admin_Area in L3 
- impact values, the *_Min in L1 should be smaller or equal to sum of *_Min in L2, and the *_Max in L1 should be larger or equal to the sum of *_Max in L2. The *_Min in L2 of one Admin_Area (ignore the record where several countries have one value of impact) should be smaller or equal to sum of *_Min in the same Admin_Area in L3, and the The *_Max in L2 of one Admin_Area (ignore the record where several countries have one value of impact) should be larger or equal to sum of *_Max in the same Admin_Area in L3.
