### ISSUE TITLE
Checklist of changes and todo (need prove from at least Wim and Joakim) 

### ISSUE THREAD

**Issue by liniiiiii** [VUB-HYDR/Wikimpacts#72]
Hi All,
    Thanks for the super productive meeting, and here I listed the changes we would make and pls help to comment and confirm before 16th Friday, earlier is better and super appreciated!  

- [ ] **Single or multi events classification**: @MurathanKurfali  used the Lama model to classify under the unsupervised learning approach, and the prediction is mostly matching with @liniiiiii  manual classification. **Todo**: clarify the definition and classification rules. **responsibility**  @liniiiiii @MurathanKurfali 
- [ ] **Location in each event level**, as discussed in the meeting, we select to use the **country** level for all event levels, and for specific_instance add one variable "**Adminstrative_Area**" which contains lower level than country. Declaim neural for location respective. **Todo**: a) extract and normalize a list of country from location column both from gold and raw output in all levels b) change the Location to Adminstrative_Area (can be done only in the final database, not necessary to change in the evaluation matrix?)  **responsibility**: @i-be-snek @liniiiiii 
- [ ] **Location normalization**: some locations are too old to use in current stage, especially when we include events from ancient times (like back to the year 1030), some locations are wrongly typoed in Wikipedia, which leads to error in normalization.  **Todo**: leave these locations in a list of strings without normalization, and in evaluation, we evaluate them as the same as recognized locations.  **responsibility**: @i-be-snek @liniiiiii 
- [ ] **Level of information**: based on the gold data, the database structure from sub-main event to impact_location structure, and to have a user-friendly structure in the final database, and also present the confidence of each level, we now have L1: impact in total, with a list of all affected countries; L2: impact in national level, with a list of affected countries (is different from the L1, because normally only one country in this list); L3: impact in sub-national level, with one country, and a list of affected locations.  **Todo**: a) parse the three levels of information from raw output (@liniiiiii already revised the parse_events.py for this, but need @i-be-snek  to double check) b) evaluation for L2 and L3. **responsibility**: @i-be-snek 
- [ ] **Variable name consistency** : this is for the evaluation process, not for the final database. L1: Total_Impact* is applied; L2 and L3: Num_Min/Max.
- [ ] **evaluation for monetary damages**: currently, we have at least one currency for the damage in the gold,  but the model only gives one output with one currency, the evaluation matrix is not suitable to compare them separately. **Todo**: map if the currency matched and then compare the output, otherwise, give the penalty score.  **Responsibility**: @i-be-snek @liniiiiii 
- [ ] **evaluation of L2 and L3**: a) some events in the gold data haven't been annotated with these two level information yet due to the work load, and it doesn't mean that these events without L2 and L3 information.  b) the LLM output sometimes contains NULLs in these two levels, which means that the location is captured but without impacts, do we flag the output before go to the evaluation stage? **Todo**: filter them in the L2 and L3 evaluation. **Responsibility**: @i-be-snek @liniiiiii 
- [ ] **Annotation rules** : pls help to check the guideline and freeze it (it's already quite complete, and the dev set revised already follow the guideline https://1drv.ms/w/c/78d0e12ab2e8ce00/ER-yUbk7aghEgIoDffWZxF0Bn2WWfSimH4En3-ik3zJSQw?e=4h6usg), **Todo**: update the test set, **responsibility**: @liniiiiii 
- [ ] **prompt froze and upload in repo** : the prompt design is already adapted to the guideline and the three level information structure, if this is confirmed, then the prompt can be frozen and use for full run. **responsibility**: @liniiiiii
